title: "Portfolio"
description: "Enterprise Data Management Portfolio"
author: Samia, John Melvin P.
remote_theme: pages-themes/time-machine@v0.2.0
logo: ""

show_downloads: true

github:
  is_project_page: true

plugins:
  - jekyll-remote-theme

include:
  - images
